# Generated by Django 5.2.1 on 2025-06-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_questtopic_quest_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='points',
            field=models.PositiveIntegerField(default=75, help_text='Очки, которые получает пользователь за прохождение квеста'),
        ),
    ]
