# Generated by Django 5.2.1 on 2025-05-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('finance', 'Финансовая грамотность'), ('economy', 'Экономика'), ('stocks', 'Фондовый рынок')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Простая'), ('medium', 'Средняя'), ('hard', 'Сложная')], max_length=10)),
                ('image', models.ImageField(default='default_course.png', upload_to='course_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
