# Generated by Django 5.2.1 on 2025-05-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.AddField(
            model_name='course',
            name='tokens',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Финансовая грамотность', 'Финансовая грамотность'), ('Экономика', 'Экономика'), ('Фондовый рынок', 'Фондовый рынок')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Lv. 1'), ('3', 'Lv. 3'), ('5', 'Lv. 5'), ('7', 'Lv. 7'), ('10', 'Lv. 10')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
