# Generated by Django 5.2.1 on 2025-05-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_created_at_course_tokens_course_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Легкий'), ('2', 'Средний'), ('3', 'Сложный')], default='1', max_length=2),
        ),
    ]
