# Generated by Django 5.2.1 on 2025-05-14 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursecompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercoursecompletion',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(related_name='enrolled_courses', through='courses.UserCourse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CourseCompletion',
        ),
    ]
