# Generated by Django 5.2.1 on 2025-06-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_usercoursecompletion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='points',
            field=models.PositiveIntegerField(default=100, help_text='Очки, которые получает пользователь за прохождение курса'),
        ),
    ]
