# Generated by Django 5.2.1 on 2025-06-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(1, 'Начинающий'), (2, 'Продвинутый')], default=1)),
                ('points', models.PositiveIntegerField(default=0)),
                ('points_to_next_level', models.PositiveIntegerField(default=1000)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userlevel'),
        ),
    ]
