# Generated by Django 5.2.1 on 2025-06-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlevel_profile_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(default='achievements/default.png', upload_to='achievements/')),
                ('condition_type', models.CharField(choices=[('courses_completed', 'Завершено курсов'), ('tests_completed', 'Завершено тестов'), ('quests_completed', 'Завершено квестов'), ('all_courses', 'Все курсы пройдены'), ('perfect_score', 'Идеальный результат')], max_length=50)),
                ('condition_value', models.IntegerField(default=0)),
                ('points_reward', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.achievement'),
        ),
    ]
